### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by michaelgaida** [gerva/tower-companion#13]
for obvious reason...

**Comment by gerva** [comment]
It's always a great idea :)

**Comment by gerva** [comment]
@michaelgaida I've integrated this project with travis and coveralls, as soon you have tests, drop them in test/ and... don't break the build 😄

**Comment by gerva** [comment]
@michaelgaida #22 brings coverage to 99%, can you add the missing tests :)

**Comment by gerva** [comment]
closed by #22 and version 0.1.4 (100% coverage)
