### ISSUE TITLE
Make reckless_mode configurable as environment variable

### ISSUE THREAD

**Issue by michaelgaida** [gerva/tower-companion#7]
Since reckless_mode is not a tower-cli variable this can't be done by a
`ansible-cli config reckless_mode [value]`
Instead it must be implemented as file operation which modifies ~/.tower_cli.cfg

As soon as this is done, this variable can be added in the docker-composer.yml and following steps can be removed from the Dockerfile:

`RUN echo "[general]" > ~/.tower_cli.cfg`
`RUN echo "reckless_mode = yes" >> ~/.tower_cli.cfg`

**Comment by gerva** [comment]
Closed by #17
